version: "3.7"

services:
  mjpg-streamer:
#    image: ha.theycallmedotcom.com:7443/stevenson/mjpg-streamer:latest
    build:
      context: ./mjpg-streamer
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports:
      - 8080:8080
    environment:
      - INPUT_FLAGS=-r 1920x1080 -f 30
      - OUTPUT_FLAGS=-w ./www
    volumes:
      - /run/udev:/run/udev:ro
#    deploy:
#      restart_policy:
#        condition: none
#      placement:
#        constraints: [node.labels.octopi == 1]

  octoprint:
    image: octoprint/octoprint:latest
    restart: always
    privileged: true
    ports:
      - 80:80
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - octoprint:/octoprint
      - /proc/cpuinfo:/proc/cpuinfo:ro
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro
      - /usr/lib/aarch64-linux-gnu/libvcos.so.0:/usr/lib/aarch64-linux-gnu/libvcos.so.0:ro
      - /usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:/usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:ro
 #   deploy:
 #     restart_policy:
 #       condition: none
 #     placement:
 #       constraints: [node.labels.octopi == 1]

volumes:
  octoprint:
